import Sidebar from "@/components/Sidebar/Sidebar";
import "../globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import ReduxProvider from "@/providers/ReduxProvider";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "sonner";
import BreadCrumbComp from "@/components/BreadCrumbComp/BreadCrumbComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Maily",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${inter.className} flex w-full min-h-screen`}>
        <QueryProvider>
          <ReduxProvider>
            <Toaster richColors closeButton />
            <NextTopLoader color="#f11946" showSpinner={false} />
            <Sidebar />
            <main className="w-full flex flex-col p-5 gap-5">
              <BreadCrumbComp />
              {children}
            </main>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
