import Sidebar from "@/components/Sidebar/Sidebar";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Maily",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${inter.className} flex w-full min-h-screen`}>
        <header>
          <Sidebar />
        </header>
        <main className="w-full p-2">{children}</main>
      </body>
    </html>
  );
}
