import "../globals.css";

export const metadata = {
  title: "Auth Layout",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }) => {
  return (
    <html>
      <body className="flex items-center gap-x-2 justify-center min-h-screen">
        <main>{children}</main>
      </body>
    </html>
  );
};

export default AuthLayout;
