import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Auth Layout",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const AuthLayout = ({ children }) => {
  return (
    <html>
      <body className={`${inter.className}`}>
        <Toaster richColors position="top-right" />
        <main className="">{children}</main>
      </body>
    </html>
  );
};

export default AuthLayout;
